version: '3.1'

services:

  mongo:
    image: mongo
    container_name: container-mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ADMIN_PASS}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: container-mongo-express
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASS}
      ME_CONFIG_MONGODB_PORT: ${DB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ADMIN_PASS}
      ME_CONFIG_MONGODB_SERVER: mongo
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
